### ISSUE TITLE
Include a users nickname into a Connection

### ISSUE THREAD

**Issue by renwer** [renwer/Strix#8]
There should be some nickname associated with the client, so it will be displayed in the list of the active users and before every message sent from this user's session.
For now, the goal is just to create a field with a hardcoded value inside the Connection class and to use it in rendering active user labels (the toString method of Connection should return this nickname).

**Comment by npcode15** [comment]
Hello, may I take this issue?

**Comment by renwer** [comment]
Of course, please do

W dniu śr., 18.04.2018 o 01:49 Navneet Pandey <notifications@github.com>
napisał(a):

**Comment by npcode15** [comment]
Thanks.

**Comment by damn1kk** [comment]
Sorry, dude. I waited two days. =(

**Comment by npcode15** [comment]
Sorry?

**Comment by renwer** [comment]
Hi there!
Excuse me for missing this one, I was kind of busy
Midterm test prep and all sorts of things

Thanks a lot for your work, I really appreciate it and will merge right
after rewieving!

2018-04-19 23:54 GMT+02:00 Navneet Pandey <notifications@github.com>:

**Comment by renwer** [comment]
might take a few hours until I figure out conflict resolving with command
line xD

2018-04-20 9:54 GMT+02:00 Ігор Микитенко <mykytenko.igor99@gmail.com>:
